spring:
  application:
    name: usercenter
  profiles:
    active: dev
server:
  port: 12333
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lsj.usercenter.model.entity
